# Generated by Django 5.0.6 on 2024-05-31 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_alter_user_dob_alter_user_email_alter_user_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
    ]
