# Generated by Django 5.0.6 on 2024-05-31 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_exercises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercise',
            name='types',
            field=models.ManyToManyField(related_name='types', to='programs.type'),
        ),
        migrations.AddField(
            model_name='exercisecomment',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_comments', to='exercises.exercise'),
        ),
        migrations.AddField(
            model_name='exercisecomment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_comments_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
